### ISSUE TITLE
RejectedExecutionException with crashlytics

### ISSUE THREAD

**Issue by Ashutosh7** [JakeWharton/ProcessPhoenix#25]
When I include the fabric sdk in my application onCreate I get an exception and the new instance of the app created after `Phoenix.triggerRebirth(context)` crashes. 
When I remove the Fabric sdk initialization(`Fabric.with(this, new Crashlytics());`) this works fine.

`Failed to submit events task
                                                                      java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@d89bea4 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@294540d[Shutting down, pool size = 1, active threads = 0, queued tasks = 1, completed tasks = 12]
                                                                          at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2049)
                                                                          at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:814)
                                                                          at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:305)
                                                                          at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
                                                                          at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:635)
                                                                          at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:601)
                                                                          at com.crashlytics.android.answers.AnswersEventsHandler.executeAsync(AnswersEventsHandler.java:182)
                                                                          at com.crashlytics.android.answers.AnswersEventsHandler.processEvent(AnswersEventsHandler.java:168)
                                                                          at com.crashlytics.android.answers.AnswersEventsHandler.processEventAsync(AnswersEventsHandler.java:44)
                                                                          at com.crashlytics.android.answers.SessionAnalyticsManager.onLifecycle(SessionAnalyticsManager.java:127)
                                                                          at com.crashlytics.android.answers.AnswersLifecycleCallbacks.onActivityStarted(AnswersLifecycleCallbacks.java:26)
                                                                          at io.fabric.sdk.android.ActivityLifecycleManager$ActivityLifecycleCallbacksWrapper$1.onActivityStarted(ActivityLifecycleManager.java:111)
                                                                          at android.app.Application.dispatchActivityStarted(Application.java:207)
                                                                          at android.app.Activity.onStart(Activity.java:1190)
                                                                          at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:595)
                                                                          at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
                                                                          at com.trello.rxlifecycle.components.support.RxAppCompatActivity.onStart(RxAppCompatActivity.java:52)
                                                                          at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1248)
                                                                          at android.app.Activity.performStart(Activity.java:6696)
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2628)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                          at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                          at android.os.Looper.loop(Looper.java:154)
                                                                          at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

**Comment by JakeWharton** [comment]
Check isPhoenixProcess in your application and don't initialize Fabric?

**Comment by nativ18** [comment]
I'm experiencing the exact thing, @Ashutosh7 were you managed to find a solution for it?

**Comment by parlacom** [comment]
I'm experiencing the exact thing, any solution?

**Comment by JakeWharton** [comment]
See my comment.

**Comment by TheMakerOleguch** [comment]
I have added additional check but an error still reproduces
`if (!ProcessPhoenix.isPhoenixProcess(this)) {
            Fabric.with(this, new Crashlytics());
        }`
