### ISSUE TITLE
TaskRecord.setIntent on a null object

### ISSUE THREAD

**Issue by DanielNovak** [JakeWharton/ProcessPhoenix#26]
Hi,

we have just found this crash in Crashlytics - the stacktrace contains only ProcessPhoenix. Any idea?
It's a Nexus 9 LTE model, Android 7.1.1, no root.
I did some googling and I think it's not even related to ProcessPhoenix - more like a random platform bug.
We only have one instance of this crash.

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.XXXX.XXXX/com.jakewharton.processphoenix.ProcessPhoenix}: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.server.am.TaskRecord.setIntent(com.android.server.am.ActivityRecord)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void com.android.server.am.TaskRecord.setIntent(com.android.server.am.ActivityRecord)' on a null object reference
       at android.os.Parcel.readException(Parcel.java:1690)
       at android.os.Parcel.readException(Parcel.java:1637)
       at android.app.ActivityManagerProxy.startActivity(ActivityManagerNative.java:3101)
       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1518)
       at android.app.Activity.startActivityForResult(Activity.java:4225)
       at android.app.Activity.startActivityForResult(Activity.java:4183)
       at android.app.Activity.startActivity(Activity.java:4522)
       at android.app.Activity.startActivity(Activity.java:4490)
       at com.jakewharton.processphoenix.ProcessPhoenix.onCreate(ProcessPhoenix.java:96)
       at android.app.Activity.performCreate(Activity.java:6679)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by JakeWharton** [comment]
Yeah this looks like an Android bug. Probably some kind of race condition? I'm a bit worried that you're using this library in production though...

**Comment by DanielNovak** [comment]
@JakeWharton We have 2 use-cases for ProcessPhoenix. We have a "debug" menu in one of our applications and switching the environment will clear everything in the app and also restart it just to make sure it behaves as if started from scratch. This only in pre-production builds (we have separate Crashlytics for this).

And there is also a special case in one complicated application that I am not proud of but it works - we do not support process-death in one quite complex application. We needed to solve this at a very late stage of the project. The app is not really meant or able to recover from it (it will timeout the session anyway). We are restarting the whole process in case we discover that the application has been reconstructed after a process death to cover all edge cases. One day I will make a cleaner implementation, but for now this works :-).

**Comment by MrChriZ** [comment]
I've ran into a similar issue using CustomActivityOnCrash:
https://github.com/Ereza/CustomActivityOnCrash/issues/64

Googling really hasn't come up with much.  In our case the app is on a MotoG4 Plus Android Version: 7.0

Writing here just for any one that finds something out in the future!
