### ISSUE TITLE
Not working on Android 11

### ISSUE THREAD

**Issue by dkrivoruchko** [JakeWharton/ProcessPhoenix#38]
Stops working on Android 11.
I guess because of new package visibility restrictions.
https://developer.android.com/preview/privacy/package-visibility

**Comment by JakeWharton** [comment]
You can't query your own package by default?

**Comment by dkrivoruchko** [comment]
It looks strange but with `compileSdkVersion = 30` sample project doesn't work on latest Android 11 beta 3

```
2020-08-07 16:38:17.603 492-1704/? I/ActivityTaskManager: START u0 {flg=0x10000000 cmp=com.jakewharton.processphoenix.sample/com.jakewharton.processphoenix.ProcessPhoenix (has extras)} from uid 10152
2020-08-07 16:38:17.604 492-535/? D/EventSequenceValidator: IntentStarted during UNKNOWN. Intent { flg=0x10000000 cmp=com.jakewharton.processphoenix.sample/com.jakewharton.processphoenix.ProcessPhoenix (has extras) }
    java.lang.Throwable: EventSequenceValidator#getStackTrace
        at com.google.android.startop.iorap.EventSequenceValidator.logWarningWithStackTrace(EventSequenceValidator.java:260)
        at com.google.android.startop.iorap.EventSequenceValidator.onIntentStarted(EventSequenceValidator.java:106)
        at com.android.server.wm.LaunchObserverRegistryImpl.handleOnIntentStarted(LaunchObserverRegistryImpl.java:139)
        at com.android.server.wm.LaunchObserverRegistryImpl.lambda$veRn_GhgLZLlOHOJ0ZYT6KcfYqo(Unknown Source:0)
        at com.android.server.wm.-$$Lambda$LaunchObserverRegistryImpl$veRn_GhgLZLlOHOJ0ZYT6KcfYqo.accept(Unknown Source:10)
        at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:292)
        at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:201)
        at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:97)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.os.HandlerThread.run(HandlerThread.java:67)
        at com.android.server.ServiceThread.run(ServiceThread.java:44)
2020-08-07 16:38:17.650 492-582/? W/InputDispatcher: channel 'b61ed02 com.jakewharton.processphoenix.sample/com.jakewharton.processphoenix.sample.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
2020-08-07 16:38:17.650 492-582/? E/InputDispatcher: channel 'b61ed02 com.jakewharton.processphoenix.sample/com.jakewharton.processphoenix.sample.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
2020-08-07 16:38:17.656 492-542/? I/ActivityManager: Start proc 6989:com.jakewharton.processphoenix.sample:phoenix/u0a152 for pre-top-activity {com.jakewharton.processphoenix.sample/com.jakewharton.processphoenix.ProcessPhoenix}
2020-08-07 16:38:17.664 492-709/? I/ActivityManager: Process com.jakewharton.processphoenix.sample (pid 6914) has died: fg  TOP 
2020-08-07 16:38:17.665 492-1701/? I/WindowManager: WIN DEATH: Window{b61ed02 u0 com.jakewharton.processphoenix.sample/com.jakewharton.processphoenix.sample.MainActivity}
2020-08-07 16:38:17.665 492-1701/? W/InputDispatcher: Attempted to unregister already unregistered input channel 'b61ed02 com.jakewharton.processphoenix.sample/com.jakewharton.processphoenix.sample.MainActivity (server)'
2020-08-07 16:38:17.800 6989-6989/com.jakewharton.processphoenix.sample D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2020-08-07 16:38:17.801 6989-6989/com.jakewharton.processphoenix.sample D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2020-08-07 16:38:17.858 6989-7015/com.jakewharton.processphoenix.sample D/libEGL: loaded /vendor/lib/egl/libEGL_emulation.so
2020-08-07 16:38:17.867 6989-7015/com.jakewharton.processphoenix.sample D/libEGL: loaded /vendor/lib/egl/libGLESv1_CM_emulation.so
2020-08-07 16:38:17.875 6989-7015/com.jakewharton.processphoenix.sample D/libEGL: loaded /vendor/lib/egl/libGLESv2_emulation.so
2020-08-07 16:38:17.884 492-1701/? I/ActivityTaskManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10008000 pkg=com.jakewharton.processphoenix.sample cmp=com.jakewharton.processphoenix.sample/.MainActivity} from uid 10152
2020-08-07 16:38:17.893 492-3196/? W/ActivityTaskManager: Duplicate finish request for r=ActivityRecord{fc7cb5b u0 com.jakewharton.processphoenix.sample/com.jakewharton.processphoenix.ProcessPhoenix t10 f}}
2020-08-07 16:38:17.899 6989-6989/com.jakewharton.processphoenix.sample I/.sample:phoeni: System.exit called, status: 0
2020-08-07 16:38:17.899 6989-6989/com.jakewharton.processphoenix.sample I/AndroidRuntime: VM exiting with result code 0, cleanup skipped.
2020-08-07 16:38:17.925 492-811/? I/ActivityManager: Process com.jakewharton.processphoenix.sample:phoenix (pid 6989) has died: fg  TOP 
2020-08-07 16:38:18.111 492-535/? W/ActivityTaskManager: Activity top resumed state loss timeout for ActivityRecord{bd02362 u0 com.jakewharton.processphoenix.sample/.MainActivity t-1 f}}
2020-08-07 16:38:18.311 492-1701/? I/ActivityManager: Force stopping com.jakewharton.processphoenix.sample appid=10152 user=0: from pid 7020
2020-08-07 16:38:18.311 492-1701/? I/WindowManager:   Force finishing activity ActivityRecord{ad38ec3 u0 com.jakewharton.processphoenix.sample/.MainActivity t10}
2020-08-07 16:38:18.327 492-1701/? I/WindowManager:   Force finishing activity ActivityRecord{ad38ec3 u0 com.jakewharton.processphoenix.sample/.MainActivity t10 f} isExiting}
2020-08-07 16:38:18.327 492-1701/? W/ActivityTaskManager: Duplicate finish request for r=ActivityRecord{ad38ec3 u0 com.jakewharton.processphoenix.sample/.MainActivity t10 f} isExiting}
```

**Comment by ilyamuromets** [comment]
I have the similar problem on Pixel 3 (Android 11). The app is compiled with `targetSdkVersion 29`. But there is one difference - the app will be restarted after long period of waiting (after about 3-4 minutes).

Lib version: 2.0.0

**Comment by dkrivoruchko** [comment]
The only known solution for me is to use method with intent: `ProcessPhoenix.triggerRebirth(context, nextIntent);`

**Comment by ilyamuromets** [comment]
@dkrivoruchko which `Intent` do you use?

**Comment by dkrivoruchko** [comment]
[This one](https://github.com/JakeWharton/ProcessPhoenix/blob/92d942bbc8f36148d816c8dcf783d2d1b653bce7/sample/src/main/java/com/jakewharton/processphoenix/sample/MainActivity.java#L36). I just create manually the intent that otherwise has to be created by [this method](https://github.com/JakeWharton/ProcessPhoenix/blob/92d942bbc8f36148d816c8dcf783d2d1b653bce7/sample/src/main/java/com/jakewharton/processphoenix/sample/MainActivity.java#L30).

**Comment by ilyamuromets** [comment]
@dkrivoruchko yes, it works. Thanks!

**Comment by PaulWoitaschek** [comment]
Btw if you don't have multiple processes you can just do what this library does by just starting a new activity:

```kotlin
import android.app.Activity
import javax.inject.Inject

class ApplicationRestarter
@Inject constructor(
  private val mainActivityIntentProvider: MainActivityIntentProvider
) {

  fun restart(activity: Activity) {
    val mainActivityIntent = mainActivityIntentProvider.intent
    activity.startActivity(mainActivityIntent)
    activity.finish()
    Runtime.getRuntime().exit(0)
  }
}
```

This works fine on android 11. Does anyone see any drawbacks using this method?

**Comment by davidhowe** [comment]
I was having an issue with the application *sometimes closing without restarting (More so on our Android 10+ devices). So far this seems to work best from our latest round of testing:

```
val intent = Intent(contextRef, DEFAULT_CLASS)
intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK or Intent.FLAG_ACTIVITY_CLEAR_TASK)
contextRef.startActivity(intent)
Runtime.getRuntime().exit(0)
```

**Comment by JakeWharton** [comment]
This was fixed by https://github.com/JakeWharton/ProcessPhoenix/commit/6aa3479f6e05e3cd47c83bcfd0d34f47c65be7cd I believe. The sample works fine on Android 11.
