### ISSUE TITLE
Crash while using on Android 11

### ISSUE THREAD

**Issue by nicholaschum** [JakeWharton/ProcessPhoenix#48]
This happens on the latest ProcessPhoenix 2.1.2, as it is on a launcher, it starts up when the device boots up. Once dismissing the force close dialog, the app works fine and ProcessPhoenix continues to work.

```
02-20 01:42:58.499 10525 10525 E AndroidRuntime: FATAL EXCEPTION: main
02-20 01:42:58.499 10525 10525 E AndroidRuntime: Process: projekt.auto:phoenix, PID: 10525
02-20 01:42:58.499 10525 10525 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{projekt.auto/com.jakewharton.processphoenix.ProcessPhoenix}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.android.server.wm.Task.isActivityTypeStandardOrUndefined()' on a null object reference
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3450)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3602)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2067)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7697)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:952)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.android.server.wm.Task.isActivityTypeStandardOrUndefined()' on a null object reference
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2379)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2357)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2340)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2282)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at android.app.IActivityTaskManager$Stub$Proxy.startActivities(IActivityTaskManager.java:3730)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivitiesAsUser(Instrumentation.java:1798)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at android.app.Instrumentation.execStartActivities(Instrumentation.java:1747)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at android.app.Activity.startActivities(Activity.java:5708)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at android.app.Activity.startActivities(Activity.java:5681)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at com.jakewharton.processphoenix.ProcessPhoenix.onCreate(ProcessPhoenix.java:4)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8000)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7984)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1310)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3423)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	... 11 more
02-20 01:42:58.499 10525 10525 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at com.android.server.wm.ActivityStackSupervisor.handleNonResizableTaskIfNeeded(ActivityStackSupervisor.java:2245)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at com.android.server.wm.ActivityStackSupervisor.handleNonResizableTaskIfNeeded(ActivityStackSupervisor.java:2232)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at com.android.server.wm.ActivityStarter.startActivityInner(ActivityStarter.java:1750)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at com.android.server.wm.ActivityStarter.startActivityUnchecked(ActivityStarter.java:1526)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 	at com.android.server.wm.ActivityStarter.executeRequest(ActivityStarter.java:1190)
02-20 01:42:58.499 10525 10525 E AndroidRuntime: 
```

**Comment by nixusUM** [comment]
update

**Comment by nienienienie** [comment]
so was it fixed? what's the status?

**Comment by ahshubita** [comment]
How it fixed

**Comment by lisitso** [comment]
on Samsung TAB A (Android 11, API 30):

```
Second failure launching com.test/com.test.Splash, giving up
android.os.DeadObjectException
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:605)
	at android.app.IApplicationThread$Stub$Proxy.scheduleTransaction(IApplicationThread.java:2686)
	at android.app.servertransaction.ClientTransaction.schedule(ClientTransaction.java:136)
	at com.android.server.wm.ClientLifecycleManager.scheduleTransaction(ClientLifecycleManager.java:47)
	at com.android.server.wm.ActivityStackSupervisor.realStartActivityLocked(ActivityStackSupervisor.java:1097)
	at com.android.server.wm.ActivityStackSupervisor.startSpecificActivity(ActivityStackSupervisor.java:1247)
	at com.android.server.wm.ActivityStack.resumeTopActivityInnerLocked(ActivityStack.java:2427)
	at com.android.server.wm.ActivityStack.resumeTopActivityUncheckedLocked(ActivityStack.java:1873)
	at com.android.server.wm.RootWindowContainer.resumeFocusedStacksTopActivities(RootWindowContainer.java:2754)
	at com.android.server.wm.RootWindowContainer.resumeFocusedStacksTopActivities(RootWindowContainer.java:2687)
	at com.android.server.wm.ActivityTaskManagerService$LocalService.handleAppDied(ActivityTaskManagerService.java:8326)
	at com.android.server.am.ActivityManagerService.handleAppDiedLocked(ActivityManagerService.java:4634)
	at com.android.server.am.ActivityManagerService.appDiedLocked(ActivityManagerService.java:4878)
	at com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied(ActivityManagerService.java:1937)
	at android.os.IBinder$DeathRecipient.binderDied(IBinder.java:311)
	at android.os.BinderProxy.sendDeathNotice(BinderProxy.java:719)
```


Any idea how to make it working?

**Comment by JakeWharton** [comment]
Both of these seem like Android bugs, so unlikely there's anything to do here.
