### ISSUE TITLE
Crash when using webviews on triggerRebirth

### ISSUE THREAD

**Issue by jensdev** [JakeWharton/ProcessPhoenix#55]
Hi, I'm using the `react-native-restart` package in my RN app which uses your package. But I'm also using Webviews and when  `ProcessPhoenix.triggerRebirth(context);` is called my app crashes wiith `Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377`

Is there a way to fix this?

```
FATAL EXCEPTION: main
Process: com.myapp:phoenix, PID: 10330
java.lang.RuntimeException: Unable to create application com.myapp.MainApplication: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Current process com.myapp:phoenix (pid 10330), lock owner com.myapp (pid 9078)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6733)
	at android.app.ActivityThread.access$1500(ActivityThread.java:247)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2057)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7842)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.RuntimeException: Using WebView from more than one process at once with the same data directory is not supported. https://crbug.com/558377 : Current process com.myapp:phoenix (pid 10330), lock owner com.myapp (pid 9078)
	at org.chromium.android_webview.AwDataDirLock.b(chromium-TrichromeWebViewGoogle6432.aab-stable-567216233:187)
	at org.chromium.android_webview.AwBrowserProcess.k(chromium-TrichromeWebViewGoogle6432.aab-stable-567216233:15)
	at com.android.webview.chromium.M.d(chromium-TrichromeWebViewGoogle6432.aab-stable-567216233:181)
	at com.android.webview.chromium.M.b(chromium-TrichromeWebViewGoogle6432.aab-stable-567216233:173)
	at com.android.webview.chromium.WebViewChromiumFactoryProvider.getStatics(chromium-TrichromeWebViewGoogle6432.aab-stable-567216233:16)
	at android.webkit.WebView.setWebContentsDebuggingEnabled(WebView.java:2009)
	at com.myapp.MainApplication.onCreate(MainApplication.java:72)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6728)
	... 9 more
```

**Comment by jensdev** [comment]
Ok, I've added 
```
if (ProcessPhoenix.isPhoenixProcess(this)) {
  return;
}
```

In my `onCreate` it works nw
